<?php $this->partial('layouts/dashboard_header'); ?>

<div class="content-wrapper">

    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Setting</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="dashboard">Home</a></li>
                        <li class="breadcrumb-item active">change_password</li>
                    </ol>
                </div>
            </div>



            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Change Password</h3>
                </div>

                <div class="alert alert-success" id="successMessage" style="display : none;"></div>
                <div class="alert alert-danger" id="errorMessage" style="display : none;"></div>
                <form id="change">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="old_pass">Current Password</label>
                            <input type="password" class="form-control" name="old_pass" placeholder="Enter current password." required>
                        </div>
                        <div class="form-group">
                            <label for="new_pass">New Password</label>
                            <input type="password" class="form-control" name="new_pass" placeholder="Enter new password." required>
                        </div>
                        <div class="form-group">
                            <label for="re_pass">Retype Password</label>
                            <input type="password" class="form-control" name="re_pass" placeholder="Retype password." required>
                        </div>                  
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Change Password</button>
                    </div>
                </form>
            </div>

            <script src="../../plugins/jquery/jquery.min.js"></script>

            <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

            <script src="../../dist/js/adminlte.min.js?v=3.2.0"></script>

            <script src="../../dist/js/demo.js"></script>

            <script>
                $(document).ready(function(){

                    $("#change").on('submit', function(e){
                        e.preventDefault();
                        $.ajax({
                            type: 'POST',
                            url: 'dashboard/chpass',
                            data: new FormData(this),
                            dataType: 'json',
                            contentType: false,
                            cache: false,
                            processData:false,
                            success : function(response){
                                console.log(response);
                                if(response == 'Password changed successful !!!'){
                                    $('#successMessage').html(response);
                                    $('#successMessage').show();
                                }else{
                                    $('#errorMessage').html(response);
                                    $('#errorMessage').show();
                                }
                                location.reload();
                            },
                        });
                    });

                });

            </script>

            <?php $this->partial('layouts/dashboard_footer'); ?>