<?php $this->partial('layouts/dashboard_header'); ?>
<div class="content-wrapper">
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">

                <div class="col-sm-6">
                    <h1 class="m-0">Company Details</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Company</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <?php echo $this->flashSession->output(); ?>
    <section class="content">
        <div class="container-fluid">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Company</h3>
                </div>
                <form action='dashboard/addcmp' method="post" enctype="multipart/form-data">
                    <div class="card-body">

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-building"></i></span>
                            </div>
                            <input type="text" class="form-control" name="cname" placeholder="Enter Name">
                        </div>
                        <br>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                            </div>
                            <input type="email" class="form-control" name="email" placeholder="Enter Mail Id">
                        </div>

                        <br>


                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fab fa-facebook-f"></i></span>
                            </div>
                            <input type="text" class="form-control" name="fb_url" placeholder="Enter Facebook URL.">
                        </div>
                        <br>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fab fa-twitter"></i></span>
                            </div>
                            <input type="text" class="form-control" name="tw_url" placeholder="Enter Twitter URL.">
                        </div>
                        <br>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fab fa-youtube"></i></span>
                            </div>
                            <input type="text" class="form-control" name="yt_url" placeholder="Enter Youtube URL.">
                        </div>
                        <br>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-phone"></i></span>
                            </div>
                            <input type="tel" class="form-control" name="phone" placeholder="Enter Phone No" pattern="[0-9]{10}">
                        </div>

                        <br>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-map-marker"></i></span>
                            </div>
                            <input type="text" class="form-control" name="address" placeholder="Enter Address">
                        </div>

                        <br>
                        <div class="row" style="height:150px;">
                            <div class="col col-sm-10">
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <label class="custom-file-label" for="logo" style="font-weight : lighter;">Upload Company Logo</label>
                                            <input type="file" class="custom-file-input" onchange="readURL(this,0)" name="logo" id="logo">

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col" id="preview_image">
                                <img src="img/company/logo.png" id="previewImg" alt="Insert Image" style="width: 75%; height:auto;">
                            </div>
                        </div>

                        <br>
                        <div class="row" style="height:150px;">
                            <div class="col col-sm-10">
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="custom-file">
                                            <label class="custom-file-label" for="favicon" style="font-weight : lighter;">Upload Favicon</label>
                                            <input type="file" class="custom-file-input" onchange="readURL(this,1)" name="favicon" id="favicon">

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <img src="img/company/favicon.png" id="previewImg2" alt="Insert Image" style="width: 75%; height:auto;">
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>

        </div>
    </section>
</div>
<?php $this->partial('layouts/dashboard_footer'); ?>
<script src="plugins/jquery/jquery.min.js"></script>


<script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="../../dist/js/adminlte.min.js?v=3.2.0"></script>


<script>

    // Preview Multiple image of different input.
    function readURL(input,id) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                if(id == 1){
                    $("#previewImg2").attr("src", e.target.result);
                }else{
                    $("#previewImg").attr("src", e.target.result);
                }
               
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>