<?php $this->partial('layouts/dashboard_header'); ?>

<div class="content-wrapper">

    <section class="content-header">
        <div class="container-fluid">



            <div class="alert alert-success alert-dismissible" id="successMessage" style="display : none">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h5><i class="icon fas fa-check"></i> Success!</h5>
            </div>


            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>My Profile</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="dashboard">Home</a></li>
                        <li class="breadcrumb-item active">Profile</li>
                    </ol>
                </div>
            </div>
            <div class="row mb-2"></div>
            <div class="row mb-2">
                <div class="col-md-5">

                    <div class="card card-primary card-outline">
                        <div class="card-body box-profile">
                            <div class="text-top text-right"><button class="btn btn-notice fas fa-sm fa-edit" id="ed"></button></div>
                            <div class="text-top text-left"><i class="fab fa-lg fa-instagram"></i></div>
                            <div class="text-center">
                                <img class="profile-user-img img-fluid img-circle" src="/img/profile/<?php echo $user->profile_url; ?>" alt="User profile picture">
                            </div>
                            <h3 class="profile-username text-center"><?php echo $user->name; ?></h3>
                            <p class="text-muted text-center">Software Engineer</p>
                            <ul class="list-group list-group-unbordered mb-3">
                                <li class="list-group-item">
                                    <b>Followers</b> <a class="float-right">1,322</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Following</b> <a class="float-right">543</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Friends</b> <a class="float-right">13,287</a>
                                </li>
                            </ul>
                            <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>
                        </div>

                    </div>
                </div>
                <div class="col-md-7">

                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">About Me</h3>
                        </div>
                        <div class="card-body">
                            <div class="text-top text-right"><button class="btn btn-notice fas fa-sm fa-edit" id="ed2"></button></div>
                            <strong><i class="fas fa-envelope"></i> Email</strong>
                            <p class="text-muted">
                                <?php echo $user->email; ?>
                            </p>
                            <hr>
                            <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>
                            <p class="text-muted">Kathmandu, Nepal</p>
                            <hr>
                            <strong><i class="fas fa-user-tag"></i>Role</strong>
                            <p class="text-muted">
                                <?php echo $user->role; ?>
                            </p>
                            <hr>
                            <strong><i class="far fa-file-alt mr-1"></i> Notes</strong>
                            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                        </div>

                    </div>

                </div>
                <?php if($user->role != 'Super Admin') { ?>
                <div class="row">
                    <div class="col md-6 alert alert-danger">
                        <a href="#" onclick="destroy(<?php echo $this->session->get('auth'); ?>)" style="text-decoration : none;">Delete your account??</a>
                    </div>
                </div>
                <?php } ?>
                <!--- Profile name and pic modal-->
                <div class="modal fade" id="ppname">
                    <div class="modal-dialog">
                        <div class="modal-content bg-info">
                            <div class="modal-header">
                                <h4 class="modal-title">Edit Name and Profile Pic</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-user"></i></span>
                                    </div>

                                    <form enctype="multipart/form-data" id="formData">
                                        <input type="text" class="form-control" placeholder="Name" name="name" id="name" value="<?php echo $user->name; ?>" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-image"></i></span>
                                    </div>
                                    <input type="file" class="form-control" placeholder="Enter your profile Pic" id="file" name="file">
                                </div>
                            </div>

                            <div class="modal-footer justify-content-between">
                                <button type="submit" class="btn btn-outline-light">Save changes</button>
                                </form>
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>

                            </div>
                        </div>
                    </div>
                </div>


                <!--- Details modal-->
                <div class="modal fade" id="details">
                    <div class="modal-dialog">
                        <div class="modal-content bg-info">
                            <div class="modal-header">
                                <h4 class="modal-title">Edit Name and Profile Pic</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">

                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                    </div>

                                    <input type="email" class="form-control" placeholder="Email" id="email" value="<?php echo $user->email; ?>" required>
                                </div>
                            </div>

                            <div class="modal-footer justify-content-between">
                                <button type="button" class="btn btn-outline-light" id="saveEm">Save changes</button>
                                <button type="button" class="btn btn-outline-light" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>




            </div>

        </div>


        <script src="../../plugins/jquery/jquery.min.js"></script>

        <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

        <script src="../../dist/js/adminlte.min.js?v=3.2.0"></script>

        <script src="../../dist/js/demo.js"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

        <script>
            $(document).ready(function() {
                $('#ed').click(function() {
                    $('#ppname').modal('toggle');
                });

                $('#ed2').click(function() {
                    $('#details').modal('toggle');
                });

                $('#saveEm').click(function() {
                    var email = $('#email').val();
                    $.ajax({
                        url: "dashboard/userEdit",
                        type: "POST",
                        dataType: 'json',
                        data: {
                            email
                        },
                        success: function(response) {
                            console.log(response);
                            $('#details').modal('hide');
                            $('#successMessage').html(response);
                            $('#successMessage').show();
                            location.reload();
                        },

                    });
                });

                $("#formData").on('submit', function(e) {
                    e.preventDefault();
                    $.ajax({
                        type: 'POST',
                        url: 'dashboard/userEdit',
                        data: new FormData(this),
                        dataType: 'json',
                        contentType: false,
                        cache: false,
                        processData: false,
                        success: function(response) {
                            console.log(response);
                            $('#ppname').modal('hide');
                            $('#successMessage').html(response);
                            $('#successMessage').show();
                            location.reload();
                        }
                    });

                });
            });

            function destroy($i){
                    Swal.fire({
                        title: 'Are you sure?',
                        text: "You won't be able to revert this!",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonColor: '#3085d6',
                        cancelButtonColor: '#d33',
                        confirmButtonText: 'Yes, delete it!'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            $id = $i;
                            console.log($id);
                            $.ajax({
                                type : 'POST',
                                url : 'dashboard/destroy/'+$id,
                                success : function(res){
                                    
                                    window.location.href = 'login';
                                }
                            });
                        }
                    })
                }
        </script>

        <?php $this->partial('layouts/dashboard_footer'); ?>