<footer class="footer mt-3">
    <div class="container service">
        <div class="row">
            <div class="col-sm-6 col-lg-3">
                <div class="icon-box icon-box-side">
                    <span class="icon-box-icon">
                        <i class="icon-rocket"></i>
                    </span>

                    <div class="icon-box-content">
                        <h3 class="icon-box-title">Free Shipping</h3><!-- End .icon-box-title -->
                        <p>Orders $50 or more</p>
                    </div><!-- End .icon-box-content -->
                </div><!-- End .icon-box -->
            </div><!-- End .col-sm-6 col-lg-4 -->

            <div class="col-sm-6 col-lg-3">
                <div class="icon-box icon-box-side">
                    <span class="icon-box-icon">
                        <i class="icon-rotate-left"></i>
                    </span>

                    <div class="icon-box-content">
                        <h3 class="icon-box-title">Free Returns</h3><!-- End .icon-box-title -->
                        <p>Within 30 days</p>
                    </div><!-- End .icon-box-content -->
                </div><!-- End .icon-box -->
            </div><!-- End .col-sm-6 col-lg-4 -->

            <div class="col-sm-6 col-lg-3">
                <div class="icon-box icon-box-side">
                    <span class="icon-box-icon">
                        <i class="icon-info-circle"></i>
                    </span>

                    <div class="icon-box-content">
                        <h3 class="icon-box-title">Get 20% Off 1 Item</h3><!-- End .icon-box-title -->
                        <p>When you sign up</p>
                    </div><!-- End .icon-box-content -->
                </div><!-- End .icon-box -->
            </div><!-- End .col-sm-6 col-lg-4 -->

            <div class="col-sm-6 col-lg-3">
                <div class="icon-box icon-box-side">
                    <span class="icon-box-icon">
                        <i class="icon-life-ring"></i>
                    </span>

                    <div class="icon-box-content">
                        <h3 class="icon-box-title">We Support</h3><!-- End .icon-box-title -->
                        <p>24/7 amazing services</p>
                    </div><!-- End .icon-box-content -->
                </div><!-- End .icon-box -->
            </div><!-- End .col-sm-6 col-lg-4 -->
        </div>
    </div>

    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-12">
                    <div class="widget widget-about">
                        <img src="assets/images/demos/demo-24/logo.png" class="footer-logo" alt="Footer Logo" width="110" height="25">
                        <p>Praesent dapibus, neque id cursus ucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. </p>

                        <div class="social-icons">
                            <a href="#" class="social-icon" title="Facebook" target="_blank"><i class="icon-facebook-f"></i></a>
                            <a href="#" class="social-icon" title="Twitter" target="_blank"><i class="icon-twitter"></i></a>
                            <a href="#" class="social-icon" title="Instagram" target="_blank"><i class="icon-instagram"></i></a>
                            <a href="#" class="social-icon" title="Youtube" target="_blank"><i class="icon-youtube"></i></a>
                            <a href="#" class="social-icon" title="Pinterest" target="_blank"><i class="icon-pinterest"></i></a>
                        </div><!-- End .soial-icons -->
                    </div><!-- End .widget about-widget -->
                </div><!-- End .col-sm-12 col-lg-3 -->

                <div class="col-lg-3 col-sm-4 col-md-4">
                    <div class="widget">
                        <h4 class="widget-title">useful links</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="about.html">About Molla</a></li>
                            <li><a href="#">How to shop on Molla</a></li>
                            <li><a href="#">FAQ</a></li>
                            <li><a href="contact.html">Contact us</a></li>
                            <li><a href="/login">Log in</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-4 col-lg-3 -->

                <div class="col-lg-3 col-sm-4 col-md-4">
                    <div class="widget">
                        <h4 class="widget-title">Customer Service</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Money-back guarantee!</a></li>
                            <li><a href="#">Returns</a></li>
                            <li><a href="#">Shipping</a></li>
                            <li><a href="#">Terms and conditions</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-4 col-lg-3 -->

                <div class="col-lg-3 col-sm-4 col-md-4">
                    <div class="widget">
                        <h4 class="widget-title">My Account</h4><!-- End .widget-title -->

                        <ul class="widget-list">
                            <li><a href="#">Sign In</a></li>
                            <li><a href="cart.html">View Cart</a></li>
                            <li><a href="#">My Wishlist</a></li>
                            <li><a href="#">Track My Order</a></li>
                            <li><a href="#">Help</a></li>
                        </ul><!-- End .widget-list -->
                    </div><!-- End .widget -->
                </div><!-- End .col-sm-64 col-lg-3 -->
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <p class="footer-copyright">Copyright © 2019 Molla Store. All Rights Reserved.</p><!-- End .footer-copyright -->

            <figure class="footer-payments">
                <img src="assets/images/payments.png" alt="Payment methods" width="272" height="20">
            </figure><!-- End .footer-payments -->

        </div><!-- End .widget-about-info -->
    </div><!-- End .container -->
    </div><!-- End .footer-bottom -->
</footer>
</div>

<button id="scroll-top" title="Back to Top"><i class="icon-arrow-up"></i></button>

<div class="mobile-menu-overlay">
</div><!-- End .mobil-menu-overlay -->
<div class="mobile-menu-container mobile-menu-light">
    <div class="mobile-menu-wrapper">
        <span class="mobile-menu-close"><i class="icon-close"></i></span>

        <form action="#" method="get" class="mobile-search">
            <label for="mobile-search" class="sr-only">Search</label>
            <input type="search" class="form-control" name="mobile-search" id="mobile-search" placeholder="Search in..." required>
            <button class="btn btn-primary" type="submit"><i class="icon-search"></i></button>
        </form>

        <nav class="mobile-nav">
            <ul class="mobile-menu">
                <div class="active">
                    <a href="/">HOME</a>


                </div>
                <li>
                    <a href="category.html">SHOP</a>
                    <ul>
                        <li><a href="category-list.html">Shop List</a></li>
                        <li><a href="category-2cols.html">Shop Grid 2 Columns</a></li>
                        <li><a href="category.html">Shop Grid 3 Columns</a></li>
                        <li><a href="category-4cols.html">Shop Grid 4 Columns</a></li>
                        <li><a href="category-boxed.html"><span>Shop Boxed No Sidebar<span class="tip tip-hot">Hot</span></span></a></li>
                        <li><a href="category-fullwidth.html">Shop Fullwidth No Sidebar</a></li>
                        <li><a href="product-category-boxed.html">Product Category Boxed</a></li>
                        <li><a href="product-category-fullwidth.html"><span>Product Category Fullwidth<span class="tip tip-new">New</span></span></a></li>
                        <li><a href="cart.html">Cart</a></li>
                        <li><a href="checkout.html">Checkout</a></li>
                        <li><a href="wishlist.html">Wishlist</a></li>
                        <li><a href="#">Lookbook</a></li>
                    </ul>
                </li>
                <li>
                    <a href="about.html">ABOUT US</a>

                    <ul>
                        <li><a href="about.html">About 01</a></li>
                        <li><a href="about-2.html">About 02</a></li>
                    </ul>
                </li>
                <li>
                    <a href="blog.html">Blog</a>

                    <ul>
                        <li><a href="blog.html">Classic</a></li>
                        <li><a href="blog-listing.html">Listing</a></li>
                        <li>
                            <a href="#">Grid</a>
                            <ul>
                                <li><a href="blog-grid-2cols.html">Grid 2 columns</a></li>
                                <li><a href="blog-grid-3cols.html">Grid 3 columns</a></li>
                                <li><a href="blog-grid-4cols.html">Grid 4 columns</a></li>
                                <li><a href="blog-grid-sidebar.html">Grid sidebar</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Masonry</a>
                            <ul>
                                <li><a href="blog-masonry-2cols.html">Masonry 2 columns</a></li>
                                <li><a href="blog-masonry-3cols.html">Masonry 3 columns</a></li>
                                <li><a href="blog-masonry-4cols.html">Masonry 4 columns</a></li>
                                <li><a href="blog-masonry-sidebar.html">Masonry sidebar</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Mask</a>
                            <ul>
                                <li><a href="blog-mask-grid.html">Blog mask grid</a></li>
                                <li><a href="blog-mask-masonry.html">Blog mask masonry</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">Single Post</a>
                            <ul>
                                <li><a href="single.html">Default with sidebar</a></li>
                                <li><a href="single-fullwidth.html">Fullwidth no sidebar</a></li>
                                <li><a href="single-fullwidth-sidebar.html">Fullwidth with sidebar</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="contact.html">CONTACTS</a>

                    <ul>
                        <li><a href="contact.html">Contact 01</a></li>
                        <li><a href="contact-2.html">Contact 02</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">BUY Molla</a>
                    <ul>
                        <li><a href="elements-products.html">Products</a></li>
                        <li><a href="elements-typography.html">Typography</a></li>
                        <li><a href="elements-titles.html">Titles</a></li>
                        <li><a href="elements-banners.html">Banners</a></li>
                        <li><a href="elements-product-category.html">Product Category</a></li>
                        <li><a href="elements-video-banners.html">Video Banners</a></li>
                        <li><a href="elements-buttons.html">Buttons</a></li>
                        <li><a href="elements-accordions.html">Accordions</a></li>
                        <li><a href="elements-tabs.html">Tabs</a></li>
                        <li><a href="elements-testimonials.html">Testimonials</a></li>
                        <li><a href="elements-blog-posts.html">Blog Posts</a></li>
                        <li><a href="elements-portfolio.html">Portfolio</a></li>
                        <li><a href="elements-cta.html">Call to Action</a></li>
                        <li><a href="elements-icon-boxes.html">Icon Boxes</a></li>
                    </ul>
                </li>
            </ul>
        </nav><!-- End .mobile-nav -->

        <div class="social-icons">
            <a href="#" class="social-icon" target="_blank" title="Facebook"><i class="icon-facebook-f"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Twitter"><i class="icon-twitter"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Instagram"><i class="icon-instagram"></i></a>
            <a href="#" class="social-icon" target="_blank" title="Youtube"><i class="icon-youtube"></i></a>
        </div><!-- End .social-icons -->
    </div><!-- End .mobile-menu-wrapper -->
</div><!-- End .mobile-menu-container -->

<!-- Sign in / Register Modal -->
<div class="modal fade" id="signin-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="icon-close"></i></span>
                </button>

                <div class="form-box">
                    <div class="form-tab">
                        <ul class="nav nav-pills nav-fill" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="signin-tab" data-toggle="tab" href="#loggin" role="tab" aria-controls="signin" aria-selected="true">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="register-tab" data-toggle="tab" href="#signup" role="tab" aria-controls="register" aria-selected="false">Register</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="tab-content-5">
                            <div class="tab-pane fade show active" id="loggin" role="tabpanel" aria-labelledby="signin-tab">
                                <form action="#" id="logfrm">
                                    <span id="message"></span>
                                    <div class="form-group">
                                        <label for="email">Email Address*</label>
                                        <input type="text" class="form-control" id="email" name="email" required autocomplete="on">
                                    </div><!-- End .form-group -->

                                    <div class="form-group">
                                        <label for="password">Password *</label>
                                        <input type="password" class="form-control" id="password" name="password" required autocomplete="on">
                                    </div><!-- End .form-group -->

                                    <div class="form-footer">
                                        <button type="button" id="loginbtn" class="btn btn-outline-primary-2">
                                            <span>LOG IN</span>
                                            <i class="icon-long-arrow-right"></i>
                                        </button>

                                        <!-- <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="signin-remember" >
                                            <label class="custom-control-label" for="signin-remember">Remember Me</label> -->
                                        <!-- </div> End .custom-checkbox -->

                                        <span id="forpass" class="forgot-link" style="cursor: pointer;">Forgot Your Password?</span>
                                    </div><!-- End .form-footer -->
                                </form>
                                <div class="form-choice">
                                    <p class="text-center">or sign in with</p>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <a href="#" class="btn btn-login btn-g">
                                                <i class="icon-google"></i>
                                                Login With Google
                                            </a>
                                        </div><!-- End .col-6 -->
                                        <div class="col-sm-6">
                                            <a href="#" class="btn btn-login btn-f">
                                                <i class="icon-facebook-f"></i>
                                                Login With Facebook
                                            </a>
                                        </div><!-- End .col-6 -->
                                    </div><!-- End .row -->
                                </div><!-- End .form-choice -->
                            </div><!-- .End .tab-pane -->
                            <!-- <div class="tab-pane fade show active" id="signin" role="tabpanel" aria-labelledby="signin-tab"> -->
                            <div class="tab-pane fade" id="signup" role="tabpanel" aria-labelledby="register-tab">
                                <form action="#" id="siup">
                                    <span id="errmsg"></span>
                                    <div class="form-group">
                                        <label for="name">Enter your full name*</label>
                                        <input type="text" class="form-control" id="nam" name="nam" required autocomplete="on">
                                    </div><!-- End .form-group -->


                                    <div class="form-group">
                                        <label for="em">Your email address *</label>
                                        <input type="email" class="form-control" id="em" name="em" required autocomplete="on">
                                    </div><!-- End .form-group -->

                                    <div class="form-group">
                                        <label for="pass">Password *</label>
                                        <input type="password" class="form-control" id="pass" name="pass" required autocomplete="on">
                                    </div><!-- End .form-group -->

                                    <div class="form-group">
                                        <label for="re_pass">Re-type Password *</label>
                                        <input type="password" class="form-control" name="re_pass" id="re_pass" required autocomplete="on">
                                    </div><!-- End .form-group -->

                                    <div class="form-footer">
                                        <button type="button" id="signupBtn" class="btn btn-outline-primary-2">
                                            <span>SIGN UP</span>
                                            <i class="icon-long-arrow-right"></i>
                                        </button>

                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" id="register-policy" required>
                                            <label class="custom-control-label" for="register-policy">I agree to the <a href="#">privacy policy</a> *</label>
                                        </div><!-- End .custom-checkbox -->
                                    </div><!-- End .form-footer -->
                                </form>
                                <div class="form-choice">
                                    <p class="text-center">or sign in with</p>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <a href="#" class="btn btn-login btn-g">
                                                <i class="icon-google"></i>
                                                Login With Google
                                            </a>
                                        </div><!-- End .col-6 -->
                                        <div class="col-sm-6">
                                            <a href="#" class="btn btn-login  btn-f">
                                                <i class="icon-facebook-f"></i>
                                                Login With Facebook
                                            </a>
                                        </div><!-- End .col-6 -->
                                    </div><!-- End .row -->
                                </div><!-- End .form-choice -->
                            </div><!-- .End .tab-pane -->
                        </div><!-- End .tab-content -->
                    </div><!-- End .form-tab -->
                </div><!-- End .form-box -->
            </div><!-- End .modal-body -->
        </div><!-- End .modal-content -->
    </div><!-- End .modal-dialog -->
</div><!-- End .modal -->




<!-- <div class="container newsletter-popup-container mfp-hide" id="newsletter-popup-form">
    <div class="row justify-content-center">
        <div class="col-10">
            <div class="row no-gutters bg-white newsletter-popup-content">
                <div class="col-xl-3-5col col-lg-7 banner-content-wrap">
                    <div class="banner-content text-center">
                        <img src="assets/images/popup/newsletter/logo.png" class="logo" alt="logo" width="60" height="15">
                        <h2 class="banner-title">get <span>25<light>%</light></span> off</h2>
                        <p>Subscribe to the Molla eCommerce newsletter to receive timely updates from your favorite products.</p>
                        <form action="#">
                            <div class="input-group input-group-round">
                                <input type="email" class="form-control form-control-white" placeholder="Your Email Address" aria-label="Email Adress" required>
                                <div class="input-group-append">
                                    <button class="btn" type="submit"><span>go</span></button> -->
<!-- </div>.End .input-group-append -->
<!-- </div>.End .input-group -->
<!-- </form>
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="register-policy-2" required>
                            <label class="custom-control-label" for="register-policy-2">Do not show this popup again</label> -->
<!-- </div>End .custom-checkbox -->
<!-- </div>
                </div>
                <div class="col-xl-2-5col col-lg-5 ">
                    <img src="assets/images/popup/newsletter/img-1.jpg" class="newsletter-img" alt="newsletter">
                </div>
            </div>
        </div>
    </div>
</div> -->



<div class="modal fade" id="forgotpass-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="icon-close"></i></span>
                </button>
                <div class="form-box">
                    <div class="form-tab">
                        <span class="nav-link active" style="text-align:center; font-size:40px; font-weight: 500; color: orange;">Reset Password</span>
                        <div class="tab-content" id="tab-content-5">
                            <div class="tab-custom-content" style="font-size:25px; font-weight:400; color: red;">Please Enter your Email Address to Reset your Password.</div>
                            <div class="tab-pane fade show active">
                                <form action="#" id="logfrm">
                                    <span id="errms"></span>
                                    <div class="form-group">
                                        <label for="ema">Enter your Email Address*</label>
                                        <input type="text" class="form-control" id="ema" name="ema" required autocomplete="on">
                                    </div><!-- End .form-group -->

                                    <div class="form-footer">
                                        <button type="button" id="forgPassBtn" class="btn btn-outline-primary-2">
                                            <span>Submit</span>
                                            <i class="icon-long-arrow-right"></i>
                                        </button>
                                    </div><!-- End .form-footer -->
                                </form>
                            </div><!-- .End .tab-pane -->
                        </div><!-- End .form-tab -->
                    </div><!-- End .form-box -->
                </div><!-- End .modal-body -->
            </div><!-- End .modal-content -->
        </div><!-- End .modal-dialog -->
    </div><!-- End .modal -->
</div>


<div class="modal fade" id="verify-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="icon-close"></i></span>
                </button>
                <div class="form-box">
                    <div class="form-tab">
                        <span class="nav-link active" style="text-align:center; font-size:40px; font-weight: 500; color: orange;">Verify your Email</span>
                        <div class="tab-content" id="tab-content-5">
                            <div class="tab-pane fade show active">
                                <span id="erorrms"></span>
                                <div class="form-group">
                                    <input type="hidden" id="verusid" name="verusid">
                                    <label for="ema">A 4 digit verification code has been sent to your email. Please enter the code</label>
                                    <input type="text" class="form-control" id="code" name="code" style="border: none; border-bottom: 1px solid black; width:30%;" required autocomplete="on">
                                </div><!-- End .form-group -->
                                <div class="form-footer">
                                    <button type="button" id="codeBtn" class="btn btn-outline-primary-2">
                                        <span>Submit</span>
                                        <i class="icon-long-arrow-right"></i>
                                    </button>
                                </div><!-- End .form-footer -->
                            </div><!-- .End .tab-pane -->
                        </div><!-- End .form-tab -->
                    </div><!-- End .form-box -->
                </div><!-- End .modal-body -->
            </div><!-- End .modal-content -->
        </div><!-- End .modal-dialog -->
    </div><!-- End .modal -->
</div>


<div class="modal fade" id="changepass-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="icon-close"></i></span>
                </button>
                <div class="form-box">
                    <div class="form-tab">
                        <span class="nav-link active" style="text-align:center; font-size:40px; font-weight: 500; color: orange;">Change your Password</span>
                        <div class="tab-content" id="tab-content-5">
                            <div class="tab-pane fade show active">
                                <span id="errrms"></span>
                                <div class="form-group">
                                    <input type="hidden" id="usid" name="usid">
                                    <label for="newpass" id = "succmessg" ></label>
                                    <input type="password" class="form-control" id="newpass" name="newpass" required autocomplete="on">
                                </div><!-- End .form-group -->

                                <div class="form-group">
                                    
                                    <label for="repass"  >Re-type Password *</label>
                                    <input type="password" class="form-control" id="repass" name="repass" required autocomplete="on">
                                </div><!-- End .form-group -->


                                <div class="form-footer">
                                    <button type="button" id="changepassBtn" class="btn btn-outline-primary-2">
                                        <span>Submit</span>
                                        <i class="icon-long-arrow-right"></i>
                                    </button>
                                </div><!-- End .form-footer -->
                            </div><!-- .End .tab-pane -->
                        </div><!-- End .form-tab -->
                    </div><!-- End .form-box -->
                </div><!-- End .modal-body -->
            </div><!-- End .modal-content -->
        </div><!-- End .modal-dialog -->
    </div><!-- End .modal -->
</div>

<script src="frontend/assets/js/jquery.min.js"></script>
<script src="frontend/assets/js/bootstrap.bundle.min.js"></script>
<script src="frontend/assets/js/jquery.hoverIntent.min.js"></script>
<script src="frontend/assets/js/jquery.waypoints.min.js"></script>
<script src="frontend/assets/js/superfish.min.js"></script>
<script src="frontend/assets/js/owl.carousel.min.js"></script>
<script src="frontend/assets/js/bootstrap-input-spinner.js"></script>
<script src="frontend/assets/js/jquery.plugin.min.js"></script>
<script src="frontend/assets/js/jquery.countdown.min.js"></script>
<script src="frontend/assets/js/jquery.magnific-popup.min.js"></script>
<!-- Main JS File -->
<script src="frontend/assets/js/main.js"></script>
<script src="frontend/assets/js/demos/demo-24.js"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $(document).ready(function() {

        $('#register-tab').click(function() {
            // $('form#logfrm')[0].reset();
            $('#signin-tab').removeClass('active');

            $('#register-tab').addClass('active');
            


        })
        $('#signin-tab').click(function() {

            $('#register-tab').removeClass('active');
            $('#siup').trigger("reset");
            $('#signin-tab').addClass('active');


        })


        $('#loginbtn').click(function() {
            var email = $('#email').val();
            var password = $('#password').val();
            $.ajax({
                url: 'auth/login',
                type: 'POST',
                data: {
                    'email': email,
                    'password': password
                },

                cache: false,
                success: function(res) {
                        // console.log(res)
                    if (res.status == 'ERROR') {
                        var mess = res.messages;

                        $('span#message').html(mess);
                        
                        $('form#logfrm')[0].reset();
                        

                    } else {
                        if (res.id == null || res.id == '') {
                            window.location.href = '/';
                        } else {
                            window.location.href = res.loc;
                        }

                    }
                },

            });

        });

        $('#signupBtn').click(function() {
            var name = $('#nam').val();
            var email = $('#em').val();
            var password = $('#pass').val();
            var re_pass = $('#re_pass').val();

            $.ajax({
                url: 'auth/adduser',
                type: 'POST',
                data: {
                    'name': name,
                    'email': email,
                    'password': password,
                    're_pass': re_pass,
                },

                cache: false,
                success: function(res) {
                    $('#nam').val() = '';
                    $('#em').val() = '';
                    $('#pass').val() = '';
                    $('#re_pass').val() = '';
                    if (res.status = 'SUCCESS') {
                        $('#signin-modal').modal('hide');
                        Swal.fire({
                            position: 'center',
                            icon: 'success',
                            title: res.message,
                            showConfirmButton: false,
                            timer: 1500
                        })
                    } else {
                        $('span#errmsg').html(res.message);

                        setTimeout(function() {
                            $("span#errmsg").remove();
                        }, 5000)
                    }

                },

            });

        });

        $('#forpass').click(function() {
            $('#signin-modal').modal('hide');
            $('#forgotpass-modal').modal('show');
        });
        $('#forgPassBtn').click(function() {
            var em = $('#ema').val();

            $.ajax({
                url: 'auth/forgotpass',
                type: 'POST',
                data: {
                    'email': em
                },
                cache: false,
                success: function(res) {
                    console.log(res)
                    if (res.status == 'SUCCESS') {
                        $('#forgotpass-modal').modal('hide');
                        $('#verify-modal').modal('show');
                        $('#verusid').val(res.id);
                    } else {
                        $('span#errms').html(res.message);
                    }
                }
            })
        });


        $("#codeBtn").click(function() {
            cd = $('#code').val();
            id = $('#verusid').val();
            $.ajax({
                url: 'auth/codever',
                type: 'POST',
                data: {
                    'code': cd,
                    'id': id
                },
                success: function(res){
                    if(res.status == 'ERROR'){
                        $('span#erorrms').html(res.message);
                    }else{
                        $('#verify-modal').modal('hide');
                        $('#changepass-modal').modal('show');
                        $('#usid').val(res.id);
                        $('#succmessg').html(res.message);
                    }   
                }
            });

        });


        $('#changepassBtn').click(function(){
            newpass = $('#newpass').val();
            repass = $('#repass').val();
            usid = $('#usid').val();
            $.ajax({
                url: 'auth/chpa',
                type: 'POST',
                data: {
                    'id' : usid,
                    'newpass' : newpass,
                    'repass' : repass,
                },
                cache: false,
                success: function(res){
                   
                    if(res.status == "ERROR"){
                        $('#errrms').html(res.message);
                    }else{
                        console.log(res.status);
                        $('#changepass-modal').modal('hide');
                        $('#signin-modal').modal('show');
                        $('span#message').html(res.message);

                    }
                },
            });
        });



    });





    

    // Close the dropdown menu if the user clicks outside of it
    // window.onclick = function(event) {
    //     if (!event.target.matches('.dropbtn')) {
    //         var dropdowns = document.getElementsByClassName("dropdown-content");
    //         var i;
    //         for (i = 0; i < dropdowns.length; i++) {
    //             var openDropdown = dropdowns[i];
    //             if (openDropdown.classList.contains('show')) {
    //                 openDropdown.classList.remove('show');
    //                 document.getElementsByClassName('search-toggle').hide();
    //             }
    //         }
    //     }
    // }
</script>



</body>

<!-- molla/index-24.html  22 Nov 2019 10:02:48 GMT -->

</html>