<!DOCTYPE html>
<html>


<head>
    <title><?php echo $cmp->name; ?></title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="keywords" content="HTML5 Template">
    <meta name="description" content="Molla - Bootstrap eCommerce Template">
    <meta name="author" content="p-themes">
    <!-- Favicon -->

    <link rel="apple-touch-icon" sizes="180x180" href="public/img/company/<?php echo $cmp->favicon; ?>">
    <link rel="icon" type="image/png" sizes="32x32" href="public/img/company/<?php echo $cmp->favicon; ?>">
    <link rel="icon" type="image/png" sizes="16x16" href="public/img/company/<?php echo $cmp->favicon; ?>">
    <link rel="manifest" href="public/img/company/<?php echo $cmp->favicon; ?>">
    <link rel="mask-icon" href="public/img/company/<?php echo $cmp->favicon; ?>" color="#666666">
    <link rel="shortcut icon" href="public/img/company/<?php echo $cmp->favicon; ?>">
    <meta name="apple-mobile-web-app-title" content="Molla">
    <meta name="application-name" content="Molla">
    <meta name="msapplication-TileColor" content="#cc9966">
    <meta name="msapplication-config" content="public/frontend/assets/images/icons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <!-- Plugins CSS File -->
    <link rel="stylesheet" href="public/frontend/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="public/frontend/assets/css/plugins/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="public/frontend/assets/css/plugins/jquery.countdown.css">
    <link rel="stylesheet" href="public/frontend/assets/css/plugins/magnific-popup/magnific-popup.css">
    <!-- Main CSS File -->
    <link rel="stylesheet" href="public/frontend/assets/css/style.css">
    <link rel="stylesheet" href="public/frontend/assets/css/skins/skin-demo-24.css">
    <link rel="stylesheet" href="public/frontend/assets/css/demos/demo-24.css">

    <style>
        .banner:hover {
            box-shadow: 0 0 3px black;
            margin-top: -20px;
        }

        .menu.sf-arrows #home.sf-with-ul::after {
            content: none;
        }



        .pfn {
            display: inline-block;
        }

        .pfimg {
            border-radius: 50%;
            /* flex-basis: 40% */
            width: 40px;

        }

        .pf {
            display: flex;
            align-items: center;
            justify-content: center
        }

        /* Dropdown Button */
        .drop {
            /* background-color: #3498DB; */
            color: black;
            /* padding: 16px; */
            font-size: 16px;
            border: none;
            cursor: pointer;
            position: absolute;
            top: 15px;
            right: 50px;
        }

        .header-intro-clearance .cart-dropdown .cart-count {
            top: auto !important;
        }
        .header-intro-clearance .wishlist .wishlist-count {
            top: auto !important;
            right: auto !important;
        }
    </style>
</head>

<body>

    <div class="page-wrapper">
        <div class="background" style="background-image: url(public/frontend/img/fr_imgs/<?php echo $home->bgimg; ?>);">
            <header class="header header-intro-clearance header-24">

                <div class="header-top">
                    <div class="container">
                        <div class="header-left">
                            <a href="tel:#"><i class="icon-phone"></i>Call: 981-3347990</a>
                        </div><!-- End of header-left -->
                        <div class="header-right">
                            <ul class="top-menu ">
                                <li>
                                    <a href="#">Links</a>
                                    <ul>
                                        <li><a href="about.html">About Us</a></li>
                                        <li><a href="contact.html">Contact Us</a></li>
                                        <li>

                                            <?php if ($this->session->has('auth')) { ?>
                                                <div class="header-dropdown">
                                                    <a href="#"><?php if ($user->profile_url == null || $user->profile_url == '') { ?>
                                                            <img class='pfimg' src='img/profile/dummy.png'>
                                                        <?php } else { ?>
                                                            <img class='pfimg' src='/img/profile/<?php echo $user->profile_url; ?>'>
                                                        <?php } ?></a>
                                                    <div class="header-menu" style="background-color: grey;">
                                                        <ul>
                                                            <li><a href="javascript:void(0)" style="pointer-events: none" ><?php echo strtoupper($user->name); ?></a></li>
                                                            <li><a href="profile">My Profile</a></li>
                                                            <li><a href="#">Change Password</a></li>
                                                            <li><a href="logout">LogOut</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            <?php } else { ?>
                                                <a href="#signin-modal" data-toggle="modal"><i class="icon-user"></i>Login/Sign Up</a>

                                            <?php } ?>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>


                <div class="header-middle sticky-header">
                    <div class="header-left">
                        <button class="mobile-menu-toggler">
                            <span class="sr-only">Toggle mobile menu</span>
                            <i class="icon-bars"></i>
                        </button>

                        <a href="index.html" class="logo">
                            <img src="public/img/company/<?php echo $cmp->logo_url; ?>" alt="Pet Store" width="110" height="25">
                        </a>
                    </div><!-- End .header-left -->

                    <div class="header-center">
                        <nav class="main-nav">
                            <ul class="menu sf-arrows">
                                <li class="megamenu-container active">
                                    <a href="index.html" class="sf-with-ul" id='home'>Home</a>
                                </li>

                                <li>
                                    <a href="category.html" class="sf-with-ul">Shop</a>

                                    <div class="megamenu megamenu-md">
                                        <div class="row no-gutters">
                                            <div class="col-md-8">
                                                <div class="menu-col">
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <div class="menu-title">Shop with sidebar</div><!-- End .menu-title -->
                                                            <ul>
                                                                <li><a href="\">Shop List</a></li>
                                                                <li><a href="category-2cols.html">Shop Grid 2 Columns</a></li>
                                                                <li><a href="category.html">Shop Grid 3 Columns</a></li>
                                                                <li><a href="category-4cols.html">Shop Grid 4 Columns</a></li>
                                                                <li><a href="category-market.html"><span>Shop Market<span class="tip tip-new">New</span></span></a></li>
                                                            </ul>

                                                            <div class="menu-title">Shop no sidebar</div><!-- End .menu-title -->
                                                            <ul>
                                                                <li><a href="category-boxed.html"><span>Shop Boxed No Sidebar<span class="tip tip-hot">Hot</span></span></a></li>
                                                                <li><a href="category-fullwidth.html">Shop Fullwidth No Sidebar</a></li>
                                                            </ul>
                                                        </div><!-- End .col-md-6 -->

                                                        <div class="col-md-6">
                                                            <div class="menu-title">Product Category</div><!-- End .menu-title -->
                                                            <ul>
                                                                <li><a href="product-category-boxed.html">Product Category Boxed</a></li>
                                                                <li><a href="product-category-fullwidth.html"><span>Product Category Fullwidth<span class="tip tip-new">New</span></span></a></li>
                                                            </ul>
                                                            <div class="menu-title">Shop Pages</div><!-- End .menu-title -->
                                                            <ul>
                                                                <li><a href="cart.html">Cart</a></li>
                                                                <li><a href="checkout.html">Checkout</a></li>
                                                                <li><a href="wishlist.html">Wishlist</a></li>
                                                                <li><a href="dashboard.html">My Account</a></li>
                                                                <li><a href="#">Lookbook</a></li>
                                                            </ul>
                                                        </div><!-- End .col-md-6 -->
                                                    </div><!-- End .row -->
                                                </div><!-- End .menu-col -->
                                            </div><!-- End .col-md-8 -->

                                            <div class="col-md-4">
                                                <div class="banner banner-overlay">
                                                    <a href="category.html" class="banner banner-menu">
                                                        <img src="public/frontend/assets/images/menu/banner-1.jpg" alt="Banner">

                                                        <div class="banner-content banner-content-top">
                                                            <div class="banner-title text-white">Last <br>Chance<br><span><strong>Sale</strong></span></div><!-- End .banner-title -->
                                                        </div><!-- End .banner-content -->
                                                    </a>
                                                </div><!-- End .banner banner-overlay -->
                                            </div><!-- End .col-md-4 -->
                                        </div><!-- End .row -->
                                    </div><!-- End .megamenu megamenu-md -->
                                </li>
                                <li>
                                    <a href="product.html" class="sf-with-ul">Product</a>

                                    <div class="megamenu megamenu-sm">
                                        <div class="row no-gutters">
                                            <div class="col-md-6">
                                                <div class="menu-col">
                                                    <div class="menu-title">Product Details</div><!-- End .menu-title -->
                                                    <ul>
                                                        <li><a href="product.html">Default</a></li>
                                                        <li><a href="product-centered.html">Centered</a></li>
                                                        <li><a href="product-extended.html"><span>Extended Info<span class="tip tip-new">New</span></span></a></li>
                                                        <li><a href="product-gallery.html">Gallery</a></li>
                                                        <li><a href="product-sticky.html">Sticky Info</a></li>
                                                        <li><a href="product-sidebar.html">Boxed With Sidebar</a></li>
                                                        <li><a href="product-fullwidth.html">Full Width</a></li>
                                                        <li><a href="product-masonry.html">Masonry Sticky Info</a></li>
                                                    </ul>
                                                </div><!-- End .menu-col -->
                                            </div><!-- End .col-md-6 -->

                                            <div class="col-md-6">
                                                <div class="banner banner-overlay">
                                                    <a href="category.html">
                                                        <img src="public/frontend/assets/images/menu/banner-2.jpg" alt="Banner">

                                                        <div class="banner-content banner-content-bottom">
                                                            <div class="banner-title text-white">New Trends<br><span><strong>spring 2019</strong></span></div><!-- End .banner-title -->
                                                        </div><!-- End .banner-content -->
                                                    </a>
                                                </div><!-- End .banner -->
                                            </div><!-- End .col-md-6 -->
                                        </div><!-- End .row -->
                                    </div><!-- End .megamenu megamenu-sm -->
                                </li>
                                <li>
                                    <a href="#" class="sf-with-ul">Pages</a>


                                    <ul>
                                        <li>
                                            <a href="about.html" class="sf-with-ul">About</a>

                                            <ul>
                                                <li><a href="about.html">About 01</a></li>
                                                <li><a href="about-2.html">About 02</a></li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="contact.html" class="sf-with-ul">Contact</a>

                                            <ul>
                                                <li><a href="contact.html">Contact 01</a></li>
                                                <li><a href="contact-2.html">Contact 02</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="login.html">Login</a></li>
                                        <li><a href="faq.html">FAQs</a></li>
                                        <li><a href="404.html">Error 404</a></li>
                                        <li><a href="coming-soon.html">Coming Soon</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="blog.html" class="sf-with-ul">Blog</a>

                                    <ul>
                                        <li><a href="blog.html">Classic</a></li>
                                        <li><a href="blog-listing.html">Listing</a></li>
                                        <li>
                                            <a href="#">Grid</a>
                                            <ul>
                                                <li><a href="blog-grid-2cols.html">Grid 2 columns</a></li>
                                                <li><a href="blog-grid-3cols.html">Grid 3 columns</a></li>
                                                <li><a href="blog-grid-4cols.html">Grid 4 columns</a></li>
                                                <li><a href="blog-grid-sidebar.html">Grid sidebar</a></li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#">Masonry</a>
                                            <ul>
                                                <li><a href="blog-masonry-2cols.html">Masonry 2 columns</a></li>
                                                <li><a href="blog-masonry-3cols.html">Masonry 3 columns</a></li>
                                                <li><a href="blog-masonry-4cols.html">Masonry 4 columns</a></li>
                                                <li><a href="blog-masonry-sidebar.html">Masonry sidebar</a></li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#">Mask</a>
                                            <ul>
                                                <li><a href="blog-mask-grid.html">Blog mask grid</a></li>
                                                <li><a href="blog-mask-masonry.html">Blog mask masonry</a></li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#">Single Post</a>
                                            <ul>
                                                <li><a href="single.html">Default with sidebar</a></li>
                                                <li><a href="single-fullwidth.html">Fullwidth no sidebar</a></li>
                                                <li><a href="single-fullwidth-sidebar.html">Fullwidth with sidebar</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="elements-list.html" class="sf-with-ul">Elements</a>

                                    <ul>
                                        <li><a href="elements-products.html">Products</a></li>
                                        <li><a href="elements-typography.html">Typography</a></li>
                                        <li><a href="elements-titles.html">Titles</a></li>
                                        <li><a href="elements-banners.html">Banners</a></li>
                                        <li><a href="elements-product-category.html">Product Category</a></li>
                                        <li><a href="elements-video-banners.html">Video Banners</a></li>
                                        <li><a href="elements-buttons.html">Buttons</a></li>
                                        <li><a href="elements-accordions.html">Accordions</a></li>
                                        <li><a href="elements-tabs.html">Tabs</a></li>
                                        <li><a href="elements-testimonials.html">Testimonials</a></li>
                                        <li><a href="elements-blog-posts.html">Blog Posts</a></li>
                                        <li><a href="elements-portfolio.html">Portfolio</a></li>
                                        <li><a href="elements-cta.html">Call to Action</a></li>
                                        <li><a href="elements-icon-boxes.html">Icon Boxes</a></li>
                                    </ul>
                                </li>
                            </ul><!-- End .menu -->
                        </nav><!-- End .main-nav -->
                    </div>

                    <div class="header-right">
                        <div class="header-search">
                            <a href="#" class="search-toggle" role="button" title="Search"><i class="icon-search"></i></a>
                            <form action="#" method="get">
                                <div class="header-search-wrapper">
                                    <label for="q" class="sr-only">Search</label>
                                    <input type="search" class="form-control" name="q" id="q" placeholder="Search in..." required>
                                </div><!-- End .header-search-wrapper -->
                            </form>
                        </div><!-- End .header-search -->
                        <?php if ($this->session->has('auth')) { ?>
                            <div class="wishlist">
                                <a href="wishlist.html" title="Wishlist">
                                    <i class="icon-heart-o"></i>
                                    <span class="wishlist-count">3</span>
                                </a>
                            </div><!-- End .compare-dropdown -->

                            <div class="dropdown cart-dropdown">
                                <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-display="static">
                                    <i class="icon-shopping-cart"></i>
                                    <span class="cart-count">2</span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right">
                                    <div class="dropdown-cart-products">
                                        <div class="product">
                                            <div class="product-cart-details">
                                                <h4 class="product-title">
                                                    <a href="product.html">Beige knitted elastic runner shoes</a>
                                                </h4>

                                                <span class="cart-product-info">
                                                    <span class="cart-product-qty">1</span>
                                                    x $84.00
                                                </span>
                                            </div><!-- End .product-cart-details -->

                                            <figure class="product-image-container">
                                                <a href="product.html" class="product-image">
                                                    <img src="public/frontend/assets/images/products/cart/product-1.jpg" alt="product">
                                                </a>
                                            </figure>
                                            <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                        </div><!-- End .product -->

                                        <div class="product">
                                            <div class="product-cart-details">
                                                <h4 class="product-title">
                                                    <a href="product.html">Blue utility pinafore denim dress</a>
                                                </h4>

                                                <span class="cart-product-info">
                                                    <span class="cart-product-qty">1</span>
                                                    x $76.00
                                                </span>
                                            </div><!-- End .product-cart-details -->

                                            <figure class="product-image-container">
                                                <a href="product.html" class="product-image">
                                                    <img src="public/frontend/assets/images/products/cart/product-2.jpg" alt="product">
                                                </a>
                                            </figure>
                                            <a href="#" class="btn-remove" title="Remove Product"><i class="icon-close"></i></a>
                                        </div><!-- End .product -->
                                    </div><!-- End .cart-product -->

                                    <div class="dropdown-cart-total">
                                        <span>Total</span>

                                        <span class="cart-total-price">$160.00</span>
                                    </div><!-- End .dropdown-cart-total -->

                                    <div class="dropdown-cart-action">
                                        <a href="cart.html" class="btn btn-primary">View Cart</a>
                                        <a href="checkout.html" class="btn btn-outline-primary-2"><span>Checkout</span><i class="icon-long-arrow-right"></i></a>
                                    </div><!-- End .dropdown-cart-total -->
                                </div><!-- End .dropdown-menu -->
                            </div><!-- End .cart-dropdown -->
                        <?php } ?>
                    </div><!-- End .header-right -->
                </div><!-- End .header-middle -->
            </header><!-- End .header -->



            <!-- Sign in / Register Modal -->
            <div class="modal fade" id="signindata" tabindex="1" role="dialog" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-body">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true"><i class="icon-close"></i></span>
                            </button>

                            <div class="form-box">
                                <div class="form-tab">
                                    <ul class="nav nav-pills nav-fill" role="tablist">
                                        <li class="nav-item">
                                            <a class="nav-link active" id="signin-tab" data-toggle="tab" href="#signin" role="tab" aria-controls="signin" aria-selected="true">Sign In</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" id="register-tab" data-toggle="tab" href="#register" role="tab" aria-controls="register" aria-selected="false">Register</a>
                                        </li>
                                    </ul>
                                    <div class="tab-content" id="tab-content-5">
                                        <div class="tab-pane fade show active" id="signin" role="tabpanel" aria-labelledby="signin-tab">
                                            <form action="#">
                                                <div class="form-group">
                                                    <label for="singin-email">Username or email address *</label>
                                                    <input type="text" class="form-control" id="singin-email" name="singin-email" required>
                                                </div><!-- End .form-group -->

                                                <div class="form-group">
                                                    <label for="singin-password">Password *</label>
                                                    <input type="password" class="form-control" id="singin-password" name="singin-password" required>
                                                </div><!-- End .form-group -->

                                                <div class="form-footer">
                                                    <button type="submit" class="btn btn-outline-primary-2">
                                                        <span>LOG IN</span>
                                                        <i class="icon-long-arrow-right"></i>
                                                    </button>

                                                    <div class="custom-control custom-checkbox">
                                                        <input type="checkbox" class="custom-control-input" id="signin-remember">
                                                        <label class="custom-control-label" for="signin-remember">Remember Me</label>
                                                    </div><!-- End .custom-checkbox -->

                                                    <a href="#" class="forgot-link">Forgot Your Password?</a>
                                                </div><!-- End .form-footer -->
                                            </form>
                                            <div class="form-choice">
                                                <p class="text-center">or sign in with</p>
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <a href="#" class="btn btn-login btn-g">
                                                            <i class="icon-google"></i>
                                                            Login With Google
                                                        </a>
                                                    </div><!-- End .col-6 -->
                                                    <div class="col-sm-6">
                                                        <a href="#" class="btn btn-login btn-f">
                                                            <i class="icon-facebook-f"></i>
                                                            Login With Facebook
                                                        </a>
                                                    </div><!-- End .col-6 -->
                                                </div><!-- End .row -->
                                            </div><!-- End .form-choice -->
                                        </div><!-- .End .tab-pane -->
                                        <div class="tab-pane fade" id="register" role="tabpanel" aria-labelledby="register-tab">
                                            <form action="#">
                                                <div class="form-group">
                                                    <label for="register-email">Your email address *</label>
                                                    <input type="email" class="form-control" id="register-email" name="register-email" required>
                                                </div><!-- End .form-group -->

                                                <div class="form-group">
                                                    <label for="register-password">Password *</label>
                                                    <input type="password" class="form-control" id="register-password" name="register-password" required>
                                                </div><!-- End .form-group -->

                                                <div class="form-footer">
                                                    <button type="submit" class="btn btn-outline-primary-2">
                                                        <span>SIGN UP</span>
                                                        <i class="icon-long-arrow-right"></i>
                                                    </button>

                                                    <div class="custom-control custom-checkbox">
                                                        <input type="checkbox" class="custom-control-input" id="register-policy" required>
                                                        <label class="custom-control-label" for="register-policy">I agree to the <a href="#">privacy policy</a> *</label>
                                                    </div><!-- End .custom-checkbox -->
                                                </div><!-- End .form-footer -->
                                            </form>
                                            <div class="form-choice">
                                                <p class="text-center">or sign in with</p>
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                        <a href="#" class="btn btn-login btn-g">
                                                            <i class="icon-google"></i>
                                                            Login With Google
                                                        </a>
                                                    </div><!-- End .col-6 -->
                                                    <div class="col-sm-6">
                                                        <a href="#" class="btn btn-login  btn-f">
                                                            <i class="icon-facebook-f"></i>
                                                            Login With Facebook
                                                        </a>
                                                    </div><!-- End .col-6 -->
                                                </div><!-- End .row -->
                                            </div><!-- End .form-choice -->
                                        </div><!-- .End .tab-pane -->
                                    </div><!-- End .tab-content -->
                                </div><!-- End .form-tab -->
                            </div><!-- End .form-box -->
                        </div><!-- End .modal-body -->
                    </div><!-- End .modal-content -->
                </div><!-- End .modal-dialog -->
            </div><!-- End .modal -->